### PR TITLE
Private Events

### PR DESCRIPTION
**Pull request by marcode95**
-simple rails app about creating events
-users can signup and login with their names only
-users can create events that are separated in past and future events
-development branch was just created again due to a mistake when creating the repo

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @marcode95 
Such a remarkable project you made :+1: ! Awesome README :100: !
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Please add unit tests for model validations and associations for(Rspec) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [x] Please add integration tests for authentication (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [x] Please add integration tests for event management features(Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
- [ ] Please add the proper authentication, for example we can use [https://murmuring-mountain-41144.herokuapp.com/events/2](https://murmuring-mountain-41144.herokuapp.com/events/2) without login. (For better understanding you can watch the [video](https://www.loom.com/share/3e54a6744fd440d0be6132ebdbbd8a12))

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by marcode95** [comment]
Hey Umair!
Thanks for your help. You even created a loom video for the review - I appreciate the effort! I added tests for users, events, signup, etc., but have one issue: I created my sign-up form to keep non-signed-in users from creating events - not to keep them from seeing the events. I read through the requirements again and didn't see any specifications about blocking non-signed-in users from seeing the events. My teammates didn't do so either. I tried contacting you on slack about this a few hours ago, but the world is huge and we live in different time zones lol. I'm sorry if I missed something regarding this and look forward to the next review - thanks a lot!

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello there, You've done a great job so far on this project. However, there are still few mandatory changes you need to implement in order to get it approved 🙏😊

## **[Mandatory]**

- [x] Please update the -running the app locally instructions- in your readme file and add the ```rails db:create``` CLI before ```rails db:migrate```
- [x] Kindly refactor any logic code from your views to your app helpers (check welcome.html.erb file)
- [x] Please make sure to follow the project specifications in order to build a proper Events Attendaces structure and do the following:-

1. I should be able to attend an event. Please update your views to add the proper links to make a user be able to do that
2. The user's show page functionalities isn't 100% correct (see image below) It should display the past attended events and the future attending events, and to do that you should modify your ```def show;``` action in Users controller file, and followed with the users/show.html.erb file
current_user_show_requirement

3. Please make sure to use the ```build``` keyword in your Event ```create``` method
build_method_requirement

4. Due to the 2nd required change, you should work it out with this one. I've created 3 events and the past and the upcoming one doesn't show up in their right places and please keep in mind that a user is attending their created events by default!
Screenshot


<hr>

## **[OPTIONAL]**

- I can see in your app that there are Past Events and Future Events, but when I create an event due today, it doesn't show up in either of them. Would you please manage to put that kind of attitude in the Past Events or even better if you create a Currently Running Events section for that

<hr>

Kindly do the required changes and submit them for another review.

Good luck and happy coding 👨‍💻💻

**Comment by marcode95** [comment]
took care of everything, removed all if clauses from the views, took care of past and future events, added attend event functionality, today's events showing up now too

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @marcode95 :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Refactor the readme file on the `Getting started` section as mentioned by the previous reviewer. The step 6 is a mistake, it should be `rails db:create` nad step 8 should be `rails server` not ~~rails serve~~ 
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by marcode95** [comment]
readme file updated!

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @marcode95 ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
